name: Prettier
on: [pull_request]

env:
  FILE_PATTERN: "app/**/*.{ts,tsx}"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - name: Run Prettier
        run: |
          npx prettier --write ${FILE_PATTERN}
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply Prettier Change
